version: '3.1'
services:
  db:
    image: mysql
    container_name: userVehicleControllerApi
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - andremapa_data:/var/lib/mysql

volumes:
  andremapa_data: